name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest

      - name: Terraform Setup
        working-directory: eks-tanveer_cluster
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_BUCKET }}" \
            -backend-config="key=${{ secrets.TF_KEY }}" \
            -backend-config="region=${{ secrets.TF_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_DYNAMODB_TABLE }}"

      - name: Terraform Plan
        working-directory: eks-tanveer_cluster
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: eks-tanveer_cluster
        run: terraform apply -auto-approve tfplan

      - name: Helm Setup
        run: helm repo add stable https://charts.helm.sh/stable
        run: helm repo update

      - name: Deploy with Helm
        run: helm upgrade --install my-spring-app ./my-spring-app --namespace default --create-namespace

      - name: Clean up Infrastructure (if needed)
        if: failure()
        working-directory: eks-tanveer_cluster
        run: terraform destroy -auto-approve
