name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java (OpenJDK 17)
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install
        working-directory: path/to/your/java/project

  deploy-cluster:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        run: terraform init
        working-directory: eks-tanveer_cluster

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: eks-tanveer_cluster
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

  extract-cluster-name:
    runs-on: ubuntu-latest
    needs: deploy-cluster
    outputs:
      cluster_name: ${{ steps.terraform-output.outputs.cluster_name }}
    steps:
      - name: Get Cluster Name
        id: terraform-output
        run: echo "::set-output name=cluster_name::$(terraform output -raw eks_cluster_name | tr -d '\n')"
        working-directory: eks-tanveer_cluster

  configure-kubectl-and-helm:
    runs-on: ubuntu-latest
    needs: extract-cluster-name
    steps:
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.23.0/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Install Helm
        run: |
          curl -fsSL -o helm.tar.gz https://get.helm.sh/helm-v3.11.0-linux-amd64.tar.gz
          tar -zxvf helm.tar.gz
          sudo mv linux-amd64/helm /usr/local/bin/helm
          helm version --client

      - name: Configure kubectl to use EKS
        run: |
          CLUSTER_NAME=${{ needs.extract-cluster-name.outputs.cluster_name }}
          echo "Cluster Name: $CLUSTER_NAME"
          aws eks update-kubeconfig --name $CLUSTER_NAME --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

  deploy-helm:
    runs-on: ubuntu-latest
    needs: configure-kubectl-and-helm
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Helm Chart
        run: |
          CLUSTER_NAME=${{ needs.extract-cluster-name.outputs.cluster_name }}
          echo "Cluster Name: $CLUSTER_NAME"
          helm upgrade --install my-spring-app path/to/helm/chart --namespace default
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

  cleanup:
    runs-on: ubuntu-latest
    needs: [deploy-cluster, deploy-helm]
    if: failure()
    steps:
      - name: Notify Failure
        run: echo "One or more jobs failed. Please check the logs for details."
